### ISSUE TITLE
Build per intructions broken again

### ISSUE THREAD

**Issue by continuum-embue** [babelouest/ulfius#17]
Something has changed in the past few days. Following your INSTALL.md instructions...
Building under Debian (arm) fails:

$ cd ../yder
$ make && sudo make install

**1)**  in the yder/examples portion - "***No rule to make target 'install'. Stop"

$cd ../..
**2)** in the ulfius portion: "MHD_ALLOW_UPGRADE" undeclared.....

The first problem is immaterial - but the second is a compilation error - and I have no idea what to do about it.

Thanks. Also thanks for an excellent library.

**Comment by babelouest** [comment]
Hello,

The first problem with yder is fixed in the master branch, thanks.

The second one is probably due to your libmicrohttpd version.

To use websockets management that need `HTTP UPGRADE`, you need to install at least libmicrohttpd 0.9.53, or you can disable websocket by specifying `WEBSOCKETFLAG=-DU_DISABLE_WEBSOCKET` on make:
```
$ make WEBSOCKETFLAG=-DU_DISABLE_WEBSOCKET
```

I can't find the way to add this check in the code yet, working on it though...

**Comment by continuum-embue** [comment]
I really appreciate the quick response :) very helpful, as we're in the middle of a sprint. 
Debian (Jessie) stable libmicrohttpd is still at 0.9.37 so I will probably use the flag for now until we go to Stretch. We don't need the feature for our current release. I'll re-post if I trip over anything else...

**Comment by babelouest** [comment]
No problem, I released Ulfius 2.0 a few days ago but some bugs are still present, obviously :)

The `README.md` and  the `API.md` have been updated with the new api: https://github.com/babelouest/ulfius/blob/master/README.md#whats-new-in-ulfius-20-

**Comment by continuum-embue** [comment]
With WEBSOCKETFLAG=-DU_DISABLE_WEBSOCKET  on make (of ulfius) the initializer for mhd_flags in routine ulfius_run_mhd_daemon still fails because it's not conditionalized under U_DISABLE_WEBSOCKET when libmicrohttpd is (still) @ 0.9.37...

MHD_USE_INTERNAL_POLLING_THREAD must have arrived post 0.9.37 in libmicrohttpd,,,

**Comment by babelouest** [comment]
thanks again!

I've fixed that in the last [commit](https://github.com/babelouest/ulfius/commit/13dc8daec231c447bff067195fda47db9bde8b4c). I've tested it with an older version of MHD and a new one and it should be better now.

Don't forget to append the flag `WEBSOCKETFLAG=-DU_DISABLE_WEBSOCKET` on build.

**Comment by continuum-embue** [comment]
Confirmed "clean build" on my end. Thanks!

**Comment by babelouest** [comment]
sweet!
