### ISSUE TITLE
Make fail when disable CURL

### ISSUE THREAD

**Issue by kiwionly** [babelouest/ulfius#218]
**Describe the issue**
Hi, I was try to build the library but have fail to do so, please let me know if my steps of build was wrong, thanks !

**To Reproduce**
> git clone <ulfius_repo>
> cd <ulfius_repo>
>make

**Expected behavior**
build success

**Screenshots**
![image](https://user-images.githubusercontent.com/174617/156153032-6804d246-cb0c-47f1-9cd2-16d048369dc6.png)

**System (please complete the following information):**
- linux CENTOS 7.9
 - commit 4c963a03049cfdfe2048c509b64da612945b03da

**Additional context**

**Comment by babelouest** [comment]
Hello @kiwionly ,

I can reproduce the bug using the last commit, but the current release [2.7.7](https://github.com/babelouest/ulfius/releases/tag/v2.7.7) works fine without curl. I'll fix that asap in the master branch.

Thanks for noticing!

**Comment by babelouest** [comment]
Hello @kiwionly ,

The bug has been fixed in this commit: https://github.com/babelouest/ulfius/commit/32fa503ef161f13c6a0371246b76f84402fbe55c , can you check if it's fixed on your side as well?

**Comment by kiwionly** [comment]
@babelouest 

I try to skip GNUTLS, but seem like have issue even CRUL could skip.

![image](https://user-images.githubusercontent.com/174617/156307242-26845994-dc7c-4d8c-861b-19daf0cc581a.png)

By follow INSTALL.md, the intruction for disabled CRUL is **CURLFLAG=1**, However in [online documentation](https://babelouest.github.io/ulfius/) it show is **CURLFLAG=-DU_DISABLE_CURL**, perhaps could standardized the command ?

**Comment by babelouest** [comment]
Indeed, the API.md documentation is not consistent with INSTALL.md

I'll change the API.md (and therefore the online doc) to `XXXFLAG=1`

Concerning the `GNUTLSFLAG` issue, I can't reproduce the problem on my side, how did you install the dependencies?

**Comment by kiwionly** [comment]
I am running on the pretty old OS , centos 7.9, i think all dependencies is missing, even I install manually, still not work really smooth.

**Comment by babelouest** [comment]
Until recently, I provide Centos packages using powertools repo, check the [2.7.7 release page](https://github.com/babelouest/ulfius/releases/tag/v2.7.7)

libmicrohttpd is available in the PowerTools repo.

Maybe you can check the package build scripts to help you build ulfius on Centos:
https://github.com/babelouest/huddersfield/blob/master/docker-base/centos-latest/Dockerfile
https://github.com/babelouest/huddersfield/blob/master/ulfius/build/rpm/Dockerfile
https://github.com/babelouest/huddersfield/blob/master/ulfius/build/rpm/entrypoint.sh
